# Generated by Django 2.0.4 on 2018-06-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20180615_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='useractivity',
            unique_together=set(),
        ),
    ]
