# Generated by Django 2.0.4 on 2018-06-24 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_auto_20180615_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='feed.Post'),
        ),
    ]
